package sa.rihla.ui

import sa.rihla.R

fun textResource(key: String): Int =
    when (
        when (key) {
            "OTHER" -> "classification_other"
            "ENDED" -> "phase_ended"
            else -> key.lowercase()
        }
    ) {
        "app_name" -> R.string.app_name
        "tracking_channel" -> R.string.tracking_channel
        "tracking_active" -> R.string.tracking_active
        "tracking_notice" -> R.string.tracking_notice
        "end_journey" -> R.string.end_journey
        "start_journey" -> R.string.start_journey
        "map_unavailable" -> R.string.map_unavailable
        "dashboard" -> R.string.dashboard
        "history" -> R.string.history
        "calendar" -> R.string.calendar
        "statistics" -> R.string.statistics
        "expenses" -> R.string.expenses
        "vehicle" -> R.string.vehicle
        "settings" -> R.string.settings
        "live" -> R.string.live
        "detail" -> R.string.detail
        "welcome" -> R.string.welcome
        "intro" -> R.string.intro
        "privacy" -> R.string.privacy
        "location_explanation" -> R.string.location_explanation
        "background_explanation" -> R.string.background_explanation
        "permissions" -> R.string.permissions
        "grant_location" -> R.string.grant_location
        "grant_activity" -> R.string.grant_activity
        "grant_notifications" -> R.string.grant_notifications
        "system_settings" -> R.string.system_settings
        "background_location" -> R.string.background_location
        "home" -> R.string.home
        "university" -> R.string.university
        "configure_home" -> R.string.configure_home
        "configure_university" -> R.string.configure_university
        "no_official_boundary" -> R.string.no_official_boundary
        "finish_setup" -> R.string.finish_setup
        "manual_available" -> R.string.manual_available
        "save" -> R.string.save
        "cancel" -> R.string.cancel
        "confirm" -> R.string.confirm
        "delete" -> R.string.delete
        "delete_confirmation" -> R.string.delete_confirmation
        "delete_all" -> R.string.delete_all
        "delete_all_confirmation" -> R.string.delete_all_confirmation
        "empty" -> R.string.empty
        "distance" -> R.string.distance
        "driving_time" -> R.string.driving_time
        "stopped_time" -> R.string.stopped_time
        "total_time" -> R.string.total_time
        "university_time" -> R.string.university_time
        "university_trips" -> R.string.university_trips
        "visits" -> R.string.visits
        "outings_count" -> R.string.outings_count
        "month_distance" -> R.string.month_distance
        "month_spending" -> R.string.month_spending
        "week_university" -> R.string.week_university
        "month_university" -> R.string.month_university
        "recent" -> R.string.recent
        "tracking_status" -> R.string.tracking_status
        "idle" -> R.string.idle
        "tracking_driving" -> R.string.tracking_driving
        "tracking_stopped" -> R.string.tracking_stopped
        "at_university" -> R.string.at_university
        "at_home_pending_end" -> R.string.at_home_pending_end
        "driving_detected" -> R.string.driving_detected
        "phase_ended" -> R.string.phase_ended
        "home_to_university" -> R.string.home_to_university
        "university_to_home" -> R.string.university_to_home
        "classification_other" -> R.string.classification_other
        "classification" -> R.string.classification
        "show_map" -> R.string.show_map
        "stop" -> R.string.stop
        "visit" -> R.string.visit
        "route_legend" -> R.string.route_legend
        "attribution" -> R.string.attribution
        "map_controls" -> R.string.map_controls
        "week" -> R.string.week
        "month" -> R.string.month
        "year" -> R.string.year
        "all" -> R.string.all
        "comparison" -> R.string.comparison
        "distance_change" -> R.string.distance_change
        "spending_change" -> R.string.spending_change
        "trips_change" -> R.string.trips_change
        "travel_change" -> R.string.travel_change
        "no_comparison" -> R.string.no_comparison
        "average_visit" -> R.string.average_visit
        "average_travel" -> R.string.average_travel
        "fastest" -> R.string.fastest
        "longest" -> R.string.longest
        "fuel" -> R.string.fuel
        "food" -> R.string.food
        "other" -> R.string.other
        "total_spending" -> R.string.total_spending
        "average_spending" -> R.string.average_spending
        "cost_km" -> R.string.cost_km
        "fuel_economy" -> R.string.fuel_economy
        "insufficient_fuel" -> R.string.insufficient_fuel
        "fuel_method" -> R.string.fuel_method
        "km_l" -> R.string.km_l
        "l_100" -> R.string.l_100
        "sar_km" -> R.string.sar_km
        "add_expense" -> R.string.add_expense
        "amount" -> R.string.amount
        "liters" -> R.string.liters
        "price" -> R.string.price
        "full_tank" -> R.string.full_tank
        "expense_hint" -> R.string.expense_hint
        "invalid_expense" -> R.string.invalid_expense
        "expense_time" -> R.string.expense_time
        "outing_link" -> R.string.outing_link
        "unlinked" -> R.string.unlinked
        "active_outing" -> R.string.active_outing
        "car_name" -> R.string.car_name
        "theme" -> R.string.theme
        "system" -> R.string.system
        "light" -> R.string.light
        "dark" -> R.string.dark
        "auto_tracking" -> R.string.auto_tracking
        "allowed" -> R.string.allowed
        "denied" -> R.string.denied
        "fine_location" -> R.string.fine_location
        "activity_permission" -> R.string.activity_permission
        "notifications" -> R.string.notifications
        "current_location" -> R.string.current_location
        "map_selection" -> R.string.map_selection
        "radius" -> R.string.radius
        "polygon" -> R.string.polygon
        "polygon_hint" -> R.string.polygon_hint
        "reset_polygon" -> R.string.reset_polygon
        "location_failed" -> R.string.location_failed
        "offline_map" -> R.string.offline_map
        "offline_explanation" -> R.string.offline_explanation
        "import_map" -> R.string.import_map
        "offline_attribution" -> R.string.offline_attribution
        "offline_ready" -> R.string.offline_ready
        "offline_failed" -> R.string.offline_failed
        "tracking_failed" -> R.string.tracking_failed
        "operation_failed" -> R.string.operation_failed
        "detection_failed" -> R.string.detection_failed
        "recovery" -> R.string.recovery
        "resume" -> R.string.resume
        "gap_notice" -> R.string.gap_notice
        "month_previous" -> R.string.month_previous
        "month_next" -> R.string.month_next
        "stats_policy" -> R.string.stats_policy
        "fuel_period" -> R.string.fuel_period
        "select_date" -> R.string.select_date
        "place_required" -> R.string.place_required
        "accuracy_notice" -> R.string.accuracy_notice
        "tracking_limits" -> R.string.tracking_limits
        "data_local" -> R.string.data_local
        "done" -> R.string.done
        "started" -> R.string.started
        "ended" -> R.string.ended
        "active" -> R.string.active
        "sar" -> R.string.sar
        "km" -> R.string.km
        "minutes" -> R.string.minutes
        "hours" -> R.string.hours
        "map_source_notice" -> R.string.map_source_notice
        "duration_unit" -> R.string.duration_unit
        "confirm_import" -> R.string.confirm_import
        "no_home" -> R.string.no_home
        "no_university" -> R.string.no_university
        else -> error("Unknown UI text resource: $key")
    }
